# use container-based infrastructure
sudo: false

# test both versions of Ruby supported by Chef client 12
# elw:  Removed 2.0.0 because recent chef-zero requires 2.1.0.
rvm:
  - 2.1.0
  - 2.2.0

script:
  - bundle exec rake travis:ci
